frr version 10.4.1
frr defaults traditional
hostname ospf-igo
no ipv6 forwarding
!

router ospf
 ospf router-id 10.0.13.89
 passive-interface default
 no passive-interface eth0
 redistribute kernel metric-type 1
 network 10.0.13.0/24 area 0
!
