frr version 10.4.1
frr defaults traditional
hostname ospf-igo
no ipv6 forwarding
!

# AS4694 IDC Frontier Inc. region jp-east zones tesla, henry, pascal, joule
# https://www.idcf.jp/news/topics/20261008001
ip route 210.140.64.0/19 eth0
ip route 210.140.96.0/19 eth0
ip route 210.140.128.0/18 eth0
ip route 210.140.192.0/19 eth0

router ospf
 ospf router-id 10.0.13.89
 passive-interface default
 no passive-interface eth0
 redistribute static metric-type 1
 redistribute kernel metric-type 1
 network 10.0.13.0/24 area 0
!
